# coding: utf-8

import sys
from setuptools import setup, find_packages

NAME = "swagger_server"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "connexion",
    "swagger-ui-bundle>=0.0.2"
]

setup(
    name=NAME,
    version=VERSION,
    description="Simple Anagram API",
    author_email="laurynas.speicys@gmail.com",
    url="",
    keywords=["Swagger", "Simple Anagram API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['swagger/swagger.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['swagger_server=swagger_server.application:main']},
    long_description="""\
    A toy API that allows to populate anagram corpus and find anagrams for a give word.

    Heavily based on code generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
    """
)
