# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model


class AnagramList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, anagrams: List[str]=None):  # noqa: E501
        """AnagramList - a model defined in Swagger

        :param anagrams: The anagrams of this AnagramList.  # noqa: E501
        :type anagrams: List[str]
        """
        self.swagger_types = {
            'anagrams': List[str]
        }

        self.attribute_map = {
            'anagrams': 'anagrams'
        }
        self._anagrams = anagrams

    @classmethod
    def from_dict(cls, dikt) -> 'AnagramList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The anagram_list of this AnagramList.  # noqa: E501
        :rtype: AnagramList
        """
        pass

    @property
    def anagrams(self) -> List[str]:
        """Gets the anagrams of this AnagramList.

        array or anagrams  # noqa: E501

        :return: The anagrams of this AnagramList.
        :rtype: List[str]
        """
        return self._anagrams

    @anagrams.setter
    def anagrams(self, anagrams: List[str]):
        """Sets the anagrams of this AnagramList.

        array or anagrams  # noqa: E501

        :param anagrams: The anagrams of this AnagramList.
        :type anagrams: List[str]
        """

        self._anagrams = anagrams
