# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

import util
from models.base_model_ import Model


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, version: str=None, python_version: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param version: The version of this InlineResponse200.  # noqa: E501
        :type version: str
        :param python_version: The python_version of this InlineResponse200.  # noqa: E501
        :type python_version: str
        """
        self.swagger_types = {
            'version': str,
            'python_version': str
        }

        self.attribute_map = {
            'version': 'version',
            'python_version': 'python_version'
        }
        self._version = version
        self._python_version = python_version

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this InlineResponse200.

        Simple anagram-API version number   # noqa: E501

        :return: The version of this InlineResponse200.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this InlineResponse200.

        Simple anagram-API version number   # noqa: E501

        :param version: The version of this InlineResponse200.
        :type version: str
        """

        self._version = version

    @property
    def python_version(self) -> str:
        """Gets the python_version of this InlineResponse200.

        Python interpreter version, as returned by `sys.version`  # noqa: E501

        :return: The python_version of this InlineResponse200.
        :rtype: str
        """
        return self._python_version

    @python_version.setter
    def python_version(self, python_version: str):
        """Sets the python_version of this InlineResponse200.

        Python interpreter version, as returned by `sys.version`  # noqa: E501

        :param python_version: The python_version of this InlineResponse200.
        :type python_version: str
        """

        self._python_version = python_version
